version: '3.4'

services: 
  db:
    image: postgres:latest
    container_name: db_Machine
    environment:
      - POSTGRES_DB=Machine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdataTest:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    


  pgadmin:
    container_name: pgadmin4_Machine
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

volumes: 
  pgdataTest:
    external: true