// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WynajemMaszyn.Infrastructure;

#nullable disable

namespace WynajemMaszyn.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241017211257_totalDatabaseProject")]
    partial class totalDatabaseProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MachineryMachineryRental", b =>
                {
                    b.Property<int>("MachineryRentalsId")
                        .HasColumnType("integer");

                    b.Property<int>("MachinesId")
                        .HasColumnType("integer");

                    b.HasKey("MachineryRentalsId", "MachinesId");

                    b.HasIndex("MachinesId");

                    b.ToTable("MachineryRentalMachines", (string)null);
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.Excavator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DrivingSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnginePower")
                        .HasColumnType("integer");

                    b.Property<int>("FuelConsumption")
                        .HasColumnType("integer");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxDiggingDepth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OperatingHours")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("integer");

                    b.Property<float>("RentalPricePerDay")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeChassis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Excavators");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.ExcavatorBucket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmWidth")
                        .HasColumnType("integer");

                    b.Property<int>("BucketCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("BucketType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompatibleExcavators")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExcavatorId")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxLoadCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PinDiameter")
                        .HasColumnType("integer");

                    b.Property<int>("PinSpacing")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("integer");

                    b.Property<float>("RentalPricePerDay")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExcavatorId");

                    b.HasIndex("UserId");

                    b.ToTable("ExcavatorsBuckets");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.Harvester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuttingDiameter")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnginePower")
                        .HasColumnType("integer");

                    b.Property<int>("FuelConsumption")
                        .HasColumnType("integer");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxReach")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OperatingHours")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("integer");

                    b.Property<float>("RentalPricePerDay")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<string>("WheelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Harvesters");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.Machinery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExcavatorBucketId")
                        .HasColumnType("integer");

                    b.Property<int?>("ExcavatorId")
                        .HasColumnType("integer");

                    b.Property<int?>("HarvesterId")
                        .HasColumnType("integer");

                    b.Property<int>("IdExcavator")
                        .HasColumnType("integer");

                    b.Property<int>("IdExcavatorBucket")
                        .HasColumnType("integer");

                    b.Property<int>("IdHarvester")
                        .HasColumnType("integer");

                    b.Property<int>("IdRoller")
                        .HasColumnType("integer");

                    b.Property<int>("IdWoodChipper")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RollerId")
                        .HasColumnType("integer");

                    b.Property<int?>("WoodChipperId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExcavatorBucketId");

                    b.HasIndex("ExcavatorId");

                    b.HasIndex("HarvesterId");

                    b.HasIndex("RollerId");

                    b.HasIndex("WoodChipperId");

                    b.ToTable("Machiners");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.MachineryRental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BeginRent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndRent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MachineryRentals");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.Roller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DrivingSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("DrumWidth")
                        .HasColumnType("integer");

                    b.Property<int>("Engine")
                        .HasColumnType("integer");

                    b.Property<int>("EnginePower")
                        .HasColumnType("integer");

                    b.Property<int>("FuelConsumption")
                        .HasColumnType("integer");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVibratory")
                        .HasColumnType("boolean");

                    b.Property<bool>("KnigeAsfalt")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCompactionForce")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfDrums")
                        .HasColumnType("integer");

                    b.Property<int>("OperatingHours")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("integer");

                    b.Property<float>("RentalPricePerDay")
                        .HasColumnType("real");

                    b.Property<string>("RollerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rollers");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdPermission")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PermissionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.WoodChipper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoppingHeight")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DrivingSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnginePower")
                        .HasColumnType("integer");

                    b.Property<int>("FlowMaterial")
                        .HasColumnType("integer");

                    b.Property<int>("FuelConsumption")
                        .HasColumnType("integer");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_User")
                        .HasColumnType("integer");

                    b.Property<int>("MachineLength")
                        .HasColumnType("integer");

                    b.Property<int>("MachineWidth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OperatingHours")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("integer");

                    b.Property<float>("RentalPricePerDay")
                        .HasColumnType("real");

                    b.Property<int>("TransportHeight")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WoodChippers");
                });

            modelBuilder.Entity("MachineryMachineryRental", b =>
                {
                    b.HasOne("WynajemMaszyn.Domain.Entities.MachineryRental", null)
                        .WithMany()
                        .HasForeignKey("MachineryRentalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WynajemMaszyn.Domain.Entities.Machinery", null)
                        .WithMany()
                        .HasForeignKey("MachinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.Excavator", b =>
                {
                    b.HasOne("WynajemMaszyn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.ExcavatorBucket", b =>
                {
                    b.HasOne("WynajemMaszyn.Domain.Entities.Excavator", "Excavator")
                        .WithMany("ExcavatorBucket")
                        .HasForeignKey("ExcavatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WynajemMaszyn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excavator");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.Harvester", b =>
                {
                    b.HasOne("WynajemMaszyn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.Machinery", b =>
                {
                    b.HasOne("WynajemMaszyn.Domain.Entities.ExcavatorBucket", "ExcavatorBucket")
                        .WithMany()
                        .HasForeignKey("ExcavatorBucketId");

                    b.HasOne("WynajemMaszyn.Domain.Entities.Excavator", "Excavator")
                        .WithMany()
                        .HasForeignKey("ExcavatorId");

                    b.HasOne("WynajemMaszyn.Domain.Entities.Harvester", "Harvester")
                        .WithMany()
                        .HasForeignKey("HarvesterId");

                    b.HasOne("WynajemMaszyn.Domain.Entities.Roller", "Roller")
                        .WithMany()
                        .HasForeignKey("RollerId");

                    b.HasOne("WynajemMaszyn.Domain.Entities.WoodChipper", "WoodChipper")
                        .WithMany()
                        .HasForeignKey("WoodChipperId");

                    b.Navigation("Excavator");

                    b.Navigation("ExcavatorBucket");

                    b.Navigation("Harvester");

                    b.Navigation("Roller");

                    b.Navigation("WoodChipper");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.MachineryRental", b =>
                {
                    b.HasOne("WynajemMaszyn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.Roller", b =>
                {
                    b.HasOne("WynajemMaszyn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.User", b =>
                {
                    b.HasOne("WynajemMaszyn.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.WoodChipper", b =>
                {
                    b.HasOne("WynajemMaszyn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WynajemMaszyn.Domain.Entities.Excavator", b =>
                {
                    b.Navigation("ExcavatorBucket");
                });
#pragma warning restore 612, 618
        }
    }
}
